project:
  type: website

website:
  title: "Yann Dupis"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/yanndupis
      - icon: twitter
        href: https://twitter.com/YannDupis
      - icon: linkedin
        href: https://linkedin.com/in/yanndupis
format:
  html:
    theme: litera
    css: styles.css

